recipe updated

diff --git a/files/scripts/entrypoint b/files/scripts/entrypoint
--- a/files/scripts/entrypoint
+++ b/files/scripts/entrypoint
@@ -20,17 +20,16 @@ BASENAME=$(basename "${0}")
 ACTION_HELP=0
 ACTION_INIT=0
 ACTION_START=0
-
 JUPYTER_ADDRESS="0.0.0.0"
 JUPYTER_PORT="8888"
 JUPYTER_TOKEN=""
 START_NOTEBOOK=1
 
-__JUPYTER_WORDIR__="/work"
+__DATA_DIR__="/work"
 
 
 # Usage
-function show_usage() {
+show_usage() {
   echo "Usage: ${BASENAME} [options] (help|init|start)"
   echo "  help:"
   echo "    <none>"
@@ -38,7 +37,7 @@ function show_usage() {
   echo "    <none>"
   echo "  start:"
   echo "    -l  Starts the JypiterLab environment"
-  echo "    -n  Start the Jupyter Notebook environment (default)"
+  echo "    -n  Starts the Jupyter Notebook environment (default)"
 }
 
 
@@ -76,39 +75,40 @@ for command in "${@}"; do
       ACTION_START=1
       ;;
     *)
-      echo >&2 "  [WARN] Unknown command '${command}'"
+      #echo >&2 "  [WARN] Unknown command '${command}'"
+      exec "$@"
       ;;
   esac
 done
 
 
 # Check arguments
-if [[ $# -eq 0 ]]; then
+if [ $# -eq 0 ]; then
   show_usage
   exit 3
 fi
-if [[ "$((ACTION_HELP+ACTION_INIT+ACTION_START))" -eq 0 ]]; then
+if [ "$((ACTION_HELP+ACTION_INIT+ACTION_START))" -eq 0 ]; then
   show_usage
   exit 0
 fi
 
 
 # Check permissions
-if [[ "$(id -u)" -ne 0 ]]; then
-  echo >&2 "  [ERROR] This script requires privileged access to system files"
-  exit 4
-fi
+#if [[ "$(id -u)" -ne 0 ]]; then
+#  echo >&2 "  [ERROR] This script requires privileged access to system files"
+#  exit 4
+#fi
 
 
 # === HELP ===
-if [[ "${ACTION_HELP}" -gt 0 ]]; then
+if [ "${ACTION_HELP}" -gt 0 ]; then
   show_usage
   exit 0
 fi
 
 
 # === INIT ===
-if [[ "${ACTION_INIT}" -gt 0 ]]; then
+if [ "${ACTION_INIT}" -gt 0 ]; then
 
   # Nothing to do
   echo "  [INFO] NOTHING TO DO. run the 'start' command."
@@ -119,20 +119,20 @@ fi
 
 
 # === START ===
-if [[ "${ACTION_START}" -gt 0 ]]; then
+if [ "${ACTION_START}" -gt 0 ]; then
 
   # Create temporary dir (if needed)
-  if ! [[ -d /tmp ]]; then
+  if ! [ -d /tmp ]; then
     mkdir -m 1777 /tmp
   fi
 
   # What do we have to start...
-  if [[ "${START_NOTEBOOK}" -gt 0 ]]; then
+  if [ "${START_NOTEBOOK}" -gt 0 ]; then
     # Start the Jupyter Notebook environment
-    jupyter notebook --allow-root --no-browser --ip=${JUPYTER_ADDRESS} --port=${JUPYTER_PORT} --notebook-dir=${__JUPYTER_WORDIR__}  --NotebookApp.token=${JUPYTER_TOKEN}
+    jupyter notebook --allow-root --no-browser --ip="${JUPYTER_ADDRESS}" --port=${JUPYTER_PORT} --notebook-dir="${__DATA_DIR__}" --NotebookApp.token="${JUPYTER_TOKEN}"
   else
     # Start the Jupyter Lab environment
-    jupyter lab --allow-root --no-browser --ip=${JUPYTER_ADDRESS} --port=${JUPYTER_PORT} --notebook-dir=${__JUPYTER_WORDIR__}  --NotebookApp.token=${JUPYTER_TOKEN}
+    jupyter lab --allow-root --no-browser --ip="${JUPYTER_ADDRESS}" --port=${JUPYTER_PORT} --notebook-dir="${__DATA_DIR__}" --NotebookApp.token="${JUPYTER_TOKEN}"
   fi
 fi
 
diff --git a/files/tests/in_sanity b/files/tests/in_sanity
--- a/files/tests/in_sanity
+++ b/files/tests/in_sanity
@@ -12,70 +12,130 @@
 #
 
 # Variables
+DEBCONF_NONINTERACTIVE_SEEN="true"
+DEBIAN_FRONTEND="noninteractive"
 
-echo "=== Docker Build Test ==="
 
-echo -n "[TEST] Check if Python is installed... "
-python --version &>/dev/null
-if [[ "$?" -eq "0" ]]; then
-  echo 'OK'
-else
-  echo 'Failed'
-  exit 1
+echo '=== Docker Build Test ==='
+
+# Create temporary dir (if needed)
+if ! [ -d /tmp ]; then
+  mkdir -m 1777 /tmp
 fi
 
-echo -n "[TEST] Check if PIP is installed... "
-pip --version &>/dev/null
-if [[ "$?" -eq "0" ]]; then
-  echo 'OK'
+# load platform info
+. /etc/os-release
+
+if [ "xdebian" = "x${ID}" ] ; then
+
+  printf '[TEST] Check if apt command is installed... '
+  if dpkg -s apt > /dev/null 2>&1; then
+    echo 'OK'
+  else
+    echo 'Failed'
+    exit 1
+  fi
+
+  printf '[TEST] Check package installation with apt... '
+  if (apt-get -qq update && apt-get -y -qq install less > /dev/null 2>&1 && less --version > /dev/null 2>&1); then
+    echo 'OK'
+  else
+    echo 'Failed'
+    exit 2
+  fi
+
+  printf '[TEST] Check if debootstrap dir was removed... '
+  if [ ! -e /debootstrap ]; then
+    echo 'OK'
+  else
+    echo 'Failed'
+    exit 3
+  fi
+
+elif [ "xcentos" = "x${ID}" ] ; then
+
+  printf '[TEST] Check if yum command is installed... '
+  if rpm -q yum > /dev/null 2>&1; then
+    echo 'OK'
+  else
+    echo 'Failed'
+    exit 1
+  fi
+
+  printf '[TEST] Check package installation with yum... '
+  if (yum -y -q install less && less --version) > /dev/null 2>&1; then
+    echo 'OK'
+  else
+    echo 'Failed'
+    exit 2
+  fi
+
 else
-  echo 'Failed'
-  exit 2
+  echo '[TEST] Platform test not performed. Unknown platform.'
 fi
 
-echo -n "[TEST] Check if PIP can install modules... "
-pip install --upgrade test-pip-install &>/dev/null
-if [[ "$?" -eq "0" ]]; then
-  echo 'OK'
-else
-  echo 'Failed'
-  exit 3
-fi
-
-echo -n "[TEST] Check if PIP installed binaries into 'PATH'... "
-test-pip-install &>/dev/null
-if [[ "$?" -eq "0" ]]; then
-  echo 'OK'
-else
-  echo 'Failed'
-  exit 4
-fi
-
-echo -n "[TEST] Check if Python can find installed modules... "
-python -m test_pip_install &>/dev/null
-if [[ "$?" -eq "0" ]]; then
+printf '[TEST] Check if Python is installed... '
+if (python3 --version && python --version) > /dev/null 2>&1; then
   echo 'OK'
 else
   echo 'Failed'
   exit 5
 fi
 
-echo -n "[TEST] Check if Jupyter is installed... "
-jupyter --version &>/dev/null
-if [[ "$?" -eq "0" ]]; then
+printf '[TEST] Check if PIP is installed... '
+if (pip3 --version && pip --version) > /dev/null 2>&1; then
   echo 'OK'
 else
   echo 'Failed'
   exit 6
 fi
 
-echo -n "[TEST] Check if JupyterLab is installed... "
-jupyter-lab --version &>/dev/null
-if [[ "$?" -eq "0" ]]; then
+printf '[TEST] Check if PIP can install modules... '
+if pip install --quiet --upgrade test-pip-install > /dev/null 2>&1; then
   echo 'OK'
 else
   echo 'Failed'
   exit 7
+fi
+
+printf '[TEST] Check if PIP installed binaries into path... '
+if test-pip-install > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 8
+fi
+
+printf '[TEST] Check if Python can find installed modules... '
+if python -m test_pip_install > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 9
+fi
+
+printf '[TEST] Check if Jupyter is installed... '
+if jupyter --version > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 10
+fi
+
+printf '[TEST] Check if JupyterLab is installed... '
+if jupyter-lab --version > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 11
+fi
+
+printf '[TEST] Check if Notebook is installed... '
+if jupyter-notebook --version > /dev/null 2>&1; then
+  echo 'OK'
+else
+  echo 'Failed'
+  exit 12
 fi
 
 exit 0
